modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3"

[[mods]]
    modId="dumb_ores"
    version="${file.jarVersion}"
    displayName="Dumb Ores"
    logoFile="logo.png"
    credits="Myself"
    authors="Team Aurora"
    description="Adds a bunch of stupid ores and content that is completely devoid of sense"

[[dependencies.dumb_ores]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dumb_ores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
