modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3"

[[mods]]
    modId="tomfoolery"
    version="${file.jarVersion}"
    displayName="Tomfoolery"
    logoFile="logo.png"
    credits="Frenderman (artist), Father Toast (cool dude)"
    authors="Sarinsa"
    description="A collection of my dumbest ideas and random things, with a few additions suggested by other cool peeps!"

[[dependencies.tomfoolery]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tomfoolery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
